name: "Build firmware"

on:
  push:
    branches: [ main ]
    paths:
      - Firmware/ESP32/**
  pull_request:
    branches: [ main ]
    paths:
      - Firmware/ESP32/**

jobs:
  build-firmware-esp32:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Copy Static Files"
        run: |
          mkdir -p archive/build
          cp Firmware/ESP32/flash_esp32.sh archive/
      - name: "Build ESP32 Firmware"
        uses: ./.github/actions/build-esp-idf
        with:
          src-dir: Firmware/ESP32
          out-dir: archive/build
          app-name: openhaystack
      - name: "Create Archive"
        uses: actions/upload-artifact@v2
        with:
          name: firmware-esp32
          path: archive/*
          retention-days: 7
